import Head from 'next/head'

import Navbar from '@/component/Navbar'
import Hero from '@/component/Hero'





export default function Home() {
  return (
    <>
      <Head>
        <title>PF Saas Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
     
      </main>
     
    </>
  )
}
